### PR TITLE
Added "getActionbarHeight" method

### PR DESCRIPTION
**Pull request by mpociot**
If you ever need to get the height of the Actionbar (which I needed :D ) - here you go

### CODE REVIEW

**Comment by manumaticx** [comment]
Hi Marcel,
isn't the actionbar height just a static value of 48dp?
So, if this size is changed by theme, then this method would return the actual height as absolute pixels?

**Comment by mpociot** [comment]
No, it's not a static value. 

48dp is the default value, landscape has 40dp and on devices with the two-pane layout (tablets / sw600dp ) it's 56dp high.

**Comment by manumaticx** [comment]
ah okay, cool. thanks!

**Comment by mpociot** [comment]
But you're right - this function returns the absolute pixel (112 for example)

**Pull request merged**
