### PR TITLE
New Feature: Ability to add a custom view with a single image to the ActionBar.

### PR DESCRIPTION
**Pull request by asiby**
This pull request will add a new feature as discussed at #104

Features:

- Replace the title and subtitle of the ActionBar to an image.
- Restore the title and subtitle of the ActionBar to their previous state.
- The other icons and properties of the ActionBar stay unaltered.
- The test harness example application has been updated to support this new feature.
- The documentation has been updated.
- The version has been bumped to 1.6.10

Cheers

### CODE REVIEW

**Comment by asiby** [comment]
I have noticed that I have accidentally left some Log.i() statements in there. So before merging, you might want to delete them or change them into Log.d() so that the module doesn't flood the console.

**Comment by asiby** [comment]
I already have a patch to apply after #105. It solves an issue related to module caching in Alloy. An important variable was persisting across instances of ABX. I will prepare it and submit it.

**Comment by manumaticx** [comment]
Wow - this is an awesome pull request. I'm going to test and merge this as soon as possible. 

Thank you! 👍

**Comment by asiby** [comment]
You are very welcome. I am already using in production now.

**Comment by manumaticx** [comment]
This is really awesome. I've tested it, it works like a charm. The code looks pretty. All good. Merged. Cheers

**Pull request merged**
