### PR TITLE
Titanium 6+

### PR DESCRIPTION
**Pull request by m1ga**
Update manifest and binary

### CODE REVIEW

**Comment by manumaticx** [comment]
danke, merci, thank you, Michael :)

**Comment by m1ga** [comment]
:+1: that was schnell :)

**Comment by perdona** [comment]
Thanks, man! Do we have to rebuild the module?

**Comment by manumaticx** [comment]
That's what @m1ga did in the pull request. You can now  install v1.7.0 of the module.

**Comment by perdona** [comment]
Didn't see the dist. 👍 thanks!
This closes #110 right?

**Pull request merged**
